name: 'CroCoder JobBoard Action'
description: 'Action that gets new Job Posts.'
inputs:
  command:
    description: ''
    required: false
    default: 'GET'
  working-directory:
    description: 'Root directory'
    required: false
    default: '.'
  content-folder-path:
    description: 'Path to content folder'
    required: false
    default: 'packages/jobboard/website/content/jobs'
  changelog-folder-path:
    description: 'Path to changelog folder'
    required: false
    default: 'packages/jobboard/changelog'
  starting-branch:
    description: 'Starting branch'
    required: false
    default: master
  author-name:
    description: 'Name of the user that creates PRs.'
    required: true
  author-email:
    description: 'Email of the user that creates PRs.'
    required: true
  github-token:
    description: 'Github token of the user that creates PRs.'
    required: true
  branch-prefix:
    description: 'Branch prefix (prefix/)'
    required: false
    default: jobpost
  release-branch-prefix:
    description: 'Release branch prefix (prefix/)'
    required: false
    default: release
  commit-message:
    description: 'Short commit message that will be prepended'
    required: false
    default: 'New job found:'
  jobboard-api:
    description: 'URL of the JobBoard API'
    required: true
  jobboard-token:
    description: 'AUTH TOKEN from the JobBoard API'
    required: true
  asignees:
    description: 'Asignees'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'terminal'  
  color: 'green'